### ISSUE TITLE
dashboard.php is missing

### ISSUE THREAD

**Issue by georgemoralis** [mrserikus/adminlte_us#1]
so index.php is redirecting wrong

**Comment by mrserikus** [comment]
Dashboard.php is your custom file, where you want to redirect. I did not included it, because my dashboard had statistics and tables, what you do not need (project-specific). Feel free to contact me on discord in community support with @mr.serikus, i will help you

You can redirect at any Page, just editing path

**Comment by mrserikus** [comment]
Added additional information to readme about this issue

**Comment by georgemoralis** [comment]
cool , are they any plans to advance this? it seems quite incomplete

**Comment by mrserikus** [comment]
What exactly you want to advance? Contact me in discord better
